/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateAutomaticAnticipationSettingsRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -6112277174249643726L;
    private boolean enabled;
    private String type;
    private int volumePercentage;
    private int delay;
    private List<Integer> days;
    /** GETTER
     * 
     */
    @JsonGetter("enabled")
    public boolean getEnabled ( ) { 
        return this.enabled;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("enabled")
    public void setEnabled (boolean value) { 
        this.enabled = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("volume_percentage")
    public int getVolumePercentage ( ) { 
        return this.volumePercentage;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("volume_percentage")
    public void setVolumePercentage (int value) { 
        this.volumePercentage = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("delay")
    public int getDelay ( ) { 
        return this.delay;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("delay")
    public void setDelay (int value) { 
        this.delay = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("days")
    public List<Integer> getDays ( ) { 
        return this.days;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("days")
    public void setDays (List<Integer> value) { 
        this.days = value;
    }
 
}
