/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class CreateAntifraudRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5552014859102239083L;
    private String type;
    private CreateClearSaleRequest clearsale;
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("clearsale")
    public CreateClearSaleRequest getClearsale ( ) { 
        return this.clearsale;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("clearsale")
    public void setClearsale (CreateClearSaleRequest value) { 
        this.clearsale = value;
    }
 
}
