/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class CreatePhonesRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3027421794223735855L;
    private CreatePhoneRequest homePhone;
    private CreatePhoneRequest mobilePhone;
    /** GETTER
     * 
     */
    @JsonGetter("home_phone")
    public CreatePhoneRequest getHomePhone ( ) { 
        return this.homePhone;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("home_phone")
    public void setHomePhone (CreatePhoneRequest value) { 
        this.homePhone = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("mobile_phone")
    public CreatePhoneRequest getMobilePhone ( ) { 
        return this.mobilePhone;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("mobile_phone")
    public void setMobilePhone (CreatePhoneRequest value) { 
        this.mobilePhone = value;
    }
 
}
