/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateEmvDecryptRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8590910527998506711L;
    private String iccData;
    private String cardSequenceNumber;
    private CreateEmvDataDecryptRequest data;
    private CreateCardPaymentContactlessPOIRequest poi;
    /** GETTER
     * 
     */
    @JsonGetter("icc_data")
    public String getIccData ( ) { 
        return this.iccData;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("icc_data")
    public void setIccData (String value) { 
        this.iccData = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("card_sequence_number")
    public String getCardSequenceNumber ( ) { 
        return this.cardSequenceNumber;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("card_sequence_number")
    public void setCardSequenceNumber (String value) { 
        this.cardSequenceNumber = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("data")
    public CreateEmvDataDecryptRequest getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("data")
    public void setData (CreateEmvDataDecryptRequest value) { 
        this.data = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("poi")
    public CreateCardPaymentContactlessPOIRequest getPoi ( ) { 
        return this.poi;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("poi")
    public void setPoi (CreateCardPaymentContactlessPOIRequest value) { 
        this.poi = value;
    }
 
}
