/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetAntifraudResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8594217577777045374L;
    private String status;
    private String returnCode;
    private String returnMessage;
    private String providerName;
    private String score;
    /** GETTER
     * 
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("return_code")
    public String getReturnCode ( ) { 
        return this.returnCode;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("return_code")
    public void setReturnCode (String value) { 
        this.returnCode = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("return_message")
    public String getReturnMessage ( ) { 
        return this.returnMessage;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("return_message")
    public void setReturnMessage (String value) { 
        this.returnMessage = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("provider_name")
    public String getProviderName ( ) { 
        return this.providerName;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("provider_name")
    public void setProviderName (String value) { 
        this.providerName = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("score")
    public String getScore ( ) { 
        return this.score;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("score")
    public void setScore (String value) { 
        this.score = value;
    }
 
}
