/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetCardTokenResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7915153816906755285L;
    private String lastFourDigits;
    private String holderName;
    private String holderDocument;
    private String expMonth;
    private String expYear;
    private String brand;
    private String type;
    private String label;
    /** GETTER
     * 
     */
    @JsonGetter("last_four_digits")
    public String getLastFourDigits ( ) { 
        return this.lastFourDigits;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("last_four_digits")
    public void setLastFourDigits (String value) { 
        this.lastFourDigits = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("holder_name")
    public String getHolderName ( ) { 
        return this.holderName;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("holder_name")
    public void setHolderName (String value) { 
        this.holderName = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("holder_document")
    public String getHolderDocument ( ) { 
        return this.holderDocument;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("holder_document")
    public void setHolderDocument (String value) { 
        this.holderDocument = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("exp_month")
    public String getExpMonth ( ) { 
        return this.expMonth;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("exp_month")
    public void setExpMonth (String value) { 
        this.expMonth = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("exp_year")
    public String getExpYear ( ) { 
        return this.expYear;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("exp_year")
    public void setExpYear (String value) { 
        this.expYear = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("brand")
    public String getBrand ( ) { 
        return this.brand;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("brand")
    public void setBrand (String value) { 
        this.brand = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("label")
    public String getLabel ( ) { 
        return this.label;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("label")
    public void setLabel (String value) { 
        this.label = value;
    }
 
}
