/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.mundipagg.api.DateTimeHelper;
import org.joda.time.DateTime;

@JsonInclude(Include.ALWAYS)
public class GetOrderResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6882688645881334535L;
    private String id;
    private String code;
    private String currency;
    private List<GetOrderItemResponse> items;
    private GetCustomerResponse customer;
    private String status;
    private DateTime createdAt;
    private DateTime updatedAt;
    private List<GetChargeResponse> charges;
    private String invoiceUrl;
    private GetShippingResponse shipping;
    private LinkedHashMap<String, String> metadata;
    private List<GetCheckoutPaymentResponse> checkouts;
    private String ip;
    private String sessionId;
    private GetLocationResponse location;
    private GetDeviceResponse device;
    private boolean closed;
    /** GETTER
     * 
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("currency")
    public String getCurrency ( ) { 
        return this.currency;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("currency")
    public void setCurrency (String value) { 
        this.currency = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("items")
    public List<GetOrderItemResponse> getItems ( ) { 
        return this.items;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("items")
    public void setItems (List<GetOrderItemResponse> value) { 
        this.items = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("customer")
    public GetCustomerResponse getCustomer ( ) { 
        return this.customer;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("customer")
    public void setCustomer (GetCustomerResponse value) { 
        this.customer = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("created_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getCreatedAt ( ) { 
        return this.createdAt;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt (DateTime value) { 
        this.createdAt = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("updated_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getUpdatedAt ( ) { 
        return this.updatedAt;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("updated_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedAt (DateTime value) { 
        this.updatedAt = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("charges")
    public List<GetChargeResponse> getCharges ( ) { 
        return this.charges;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("charges")
    public void setCharges (List<GetChargeResponse> value) { 
        this.charges = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("invoice_url")
    public String getInvoiceUrl ( ) { 
        return this.invoiceUrl;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("invoice_url")
    public void setInvoiceUrl (String value) { 
        this.invoiceUrl = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("shipping")
    public GetShippingResponse getShipping ( ) { 
        return this.shipping;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("shipping")
    public void setShipping (GetShippingResponse value) { 
        this.shipping = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("metadata")
    public LinkedHashMap<String, String> getMetadata ( ) { 
        return this.metadata;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("metadata")
    public void setMetadata (LinkedHashMap<String, String> value) { 
        this.metadata = value;
    }
 
    /** GETTER
     * Checkout Payment Settings Response
     */
    @JsonGetter("checkouts")
    public List<GetCheckoutPaymentResponse> getCheckouts ( ) { 
        return this.checkouts;
    }
    
    /** SETTER
     * Checkout Payment Settings Response
     */
    @JsonSetter("checkouts")
    public void setCheckouts (List<GetCheckoutPaymentResponse> value) { 
        this.checkouts = value;
    }
 
    /** GETTER
     * Ip address
     */
    @JsonGetter("ip")
    public String getIp ( ) { 
        return this.ip;
    }
    
    /** SETTER
     * Ip address
     */
    @JsonSetter("ip")
    public void setIp (String value) { 
        this.ip = value;
    }
 
    /** GETTER
     * Session id
     */
    @JsonGetter("session_id")
    public String getSessionId ( ) { 
        return this.sessionId;
    }
    
    /** SETTER
     * Session id
     */
    @JsonSetter("session_id")
    public void setSessionId (String value) { 
        this.sessionId = value;
    }
 
    /** GETTER
     * Location
     */
    @JsonGetter("location")
    public GetLocationResponse getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * Location
     */
    @JsonSetter("location")
    public void setLocation (GetLocationResponse value) { 
        this.location = value;
    }
 
    /** GETTER
     * Device's informations
     */
    @JsonGetter("device")
    public GetDeviceResponse getDevice ( ) { 
        return this.device;
    }
    
    /** SETTER
     * Device's informations
     */
    @JsonSetter("device")
    public void setDevice (GetDeviceResponse value) { 
        this.device = value;
    }
 
    /** GETTER
     * Indicates whether the order is closed
     */
    @JsonGetter("closed")
    public boolean getClosed ( ) { 
        return this.closed;
    }
    
    /** SETTER
     * Indicates whether the order is closed
     */
    @JsonSetter("closed")
    public void setClosed (boolean value) { 
        this.closed = value;
    }
 
}
