/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetPhoneResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3293923615719918456L;
    private String countryCode;
    private String number;
    private String areaCode;
    /** GETTER
     * 
     */
    @JsonGetter("country_code")
    public String getCountryCode ( ) { 
        return this.countryCode;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("country_code")
    public void setCountryCode (String value) { 
        this.countryCode = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("number")
    public String getNumber ( ) { 
        return this.number;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("number")
    public void setNumber (String value) { 
        this.number = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("area_code")
    public String getAreaCode ( ) { 
        return this.areaCode;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("area_code")
    public void setAreaCode (String value) { 
        this.areaCode = value;
    }
 
}
