/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetPricingSchemeResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3736806292581936477L;
    private int price;
    private String schemeType;
    private List<GetPriceBracketResponse> priceBrackets;
    private Integer minimumPrice;
    private Double percentage;
    /** GETTER
     * 
     */
    @JsonGetter("price")
    public int getPrice ( ) { 
        return this.price;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("price")
    public void setPrice (int value) { 
        this.price = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("scheme_type")
    public String getSchemeType ( ) { 
        return this.schemeType;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("scheme_type")
    public void setSchemeType (String value) { 
        this.schemeType = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("price_brackets")
    public List<GetPriceBracketResponse> getPriceBrackets ( ) { 
        return this.priceBrackets;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("price_brackets")
    public void setPriceBrackets (List<GetPriceBracketResponse> value) { 
        this.priceBrackets = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("minimum_price")
    public Integer getMinimumPrice ( ) { 
        return this.minimumPrice;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("minimum_price")
    public void setMinimumPrice (Integer value) { 
        this.minimumPrice = value;
    }
 
    /** GETTER
     * percentual value used in pricing_scheme Percent
     */
    @JsonGetter("percentage")
    public Double getPercentage ( ) { 
        return this.percentage;
    }
    
    /** SETTER
     * percentual value used in pricing_scheme Percent
     */
    @JsonSetter("percentage")
    public void setPercentage (Double value) { 
        this.percentage = value;
    }
 
}
