/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetSellersRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4506300870722416743L;
    private String name;
    private String document;
    private String code;
    private String status;
    private String type;
    private String createdSince;
    private String createdUntil;
    /** GETTER
     * 
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("document")
    public String getDocument ( ) { 
        return this.document;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("document")
    public void setDocument (String value) { 
        this.document = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("created_Since")
    public String getCreatedSince ( ) { 
        return this.createdSince;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("created_Since")
    public void setCreatedSince (String value) { 
        this.createdSince = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("created_Until")
    public String getCreatedUntil ( ) { 
        return this.createdUntil;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("created_Until")
    public void setCreatedUntil (String value) { 
        this.createdUntil = value;
    }
 
}
