/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetTransferTargetResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1375102975629708481L;
    private String targetId;
    private String type;
    /** GETTER
     * 
     */
    @JsonGetter("target_id")
    public String getTargetId ( ) { 
        return this.targetId;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("target_id")
    public void setTargetId (String value) { 
        this.targetId = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
