/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.mundipagg.api.DateTimeHelper;

import org.joda.time.DateTime;

@JsonInclude(Include.ALWAYS)
public class GetTokenResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5589504862326006996L;
    private String id;
    private String type;
    private DateTime createdAt;
    private String expiresAt;
    private GetCardTokenResponse card;
    /** GETTER
     * 
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("created_at")
    @JsonSerialize(using=DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public DateTime getCreatedAt ( ) { 
        return this.createdAt;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using=DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt (DateTime value) { 
        this.createdAt = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("expires_at")
    public String getExpiresAt ( ) { 
        return this.expiresAt;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("expires_at")
    public void setExpiresAt (String value) { 
        this.expiresAt = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("card")
    public GetCardTokenResponse getCard ( ) { 
        return this.card;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("card")
    public void setCard (GetCardTokenResponse value) { 
        this.card = value;
    }
 
}
