/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class GetUsageReportResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -476802600442931274L;
    private String url;
    private String usageReportUrl;
    private String groupedReportUrl;
    /** GETTER
     * 
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("usage_report_url")
    public String getUsageReportUrl ( ) { 
        return this.usageReportUrl;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("usage_report_url")
    public void setUsageReportUrl (String value) { 
        this.usageReportUrl = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("grouped_report_url")
    public String getGroupedReportUrl ( ) { 
        return this.groupedReportUrl;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("grouped_report_url")
    public void setGroupedReportUrl (String value) { 
        this.groupedReportUrl = value;
    }
 
}
