/*
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.mundipagg.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonSetter;

@JsonInclude(Include.ALWAYS)
public class UpdateAutomaticAnticipationSettingsRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -8594674368191597587L;
    private Boolean enabled;
    private String type;
    private Integer volumePercentage;
    private Integer delay;
    private Integer days;
    /** GETTER
     * 
     */
    @JsonGetter("enabled")
    public Boolean getEnabled ( ) { 
        return this.enabled;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("enabled")
    public void setEnabled (Boolean value) { 
        this.enabled = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("volume_percentage")
    public Integer getVolumePercentage ( ) { 
        return this.volumePercentage;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("volume_percentage")
    public void setVolumePercentage (Integer value) { 
        this.volumePercentage = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("delay")
    public Integer getDelay ( ) { 
        return this.delay;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("delay")
    public void setDelay (Integer value) { 
        this.delay = value;
    }
 
    /** GETTER
     * 
     */
    @JsonGetter("days")
    public Integer getDays ( ) { 
        return this.days;
    }
    
    /** SETTER
     * 
     */
    @JsonSetter("days")
    private void setDays (Integer value) { 
        this.days = value;
    }
 
}
